Added integration tests
simonjaeger/iot-edge-opc-plc pull request #1
Opened 2021-05-17 19:46 UTC by algattik

## Purpose

* Integration tests

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: test project
```

## How to Test
```
cd tests/opc-plc-tests
dotnet test
```
## What to Check
```Passed!  - Failed:     0, Passed:    14, Skipped:     0, Total:    14, Duration: 10 s```

## Other Information

Added tests for:
- Reading values for simulated nodes (trended data nodes, random, alternating, etc.) display the expected patterns (and frequency of changes)
- Reading values for "Bad" simulated nodes have alternating status (Good, UncertainLastUsableValue, etc.)
- Writing values for nodes and reading them again, demonstrates the writing functionality
- Subscriptions receive the expected payloads, for:
  - monitored values
  - events (e.g. SystemCycleStartedEventType)
 
This first version uses static singletons to access the `TimeService` for time mocking, which should be refactored to something cleaner

2021-05-17 22:21 UTC, simonjaeger commented
Really nice! Will run this tomorrow.

2021-05-18 06:49 UTC, peterbryntesson commented on src/PlcNodeManager.cs
> +                var m = dateTime.Millisecond;
var m = .. you can clean up I guess. Looks like some left-over from debugging

2021-05-18 06:56 UTC, peterbryntesson requested changes
In general looks really good Alexandre. Will wait with approval until I can run the tests. in the meantime some clean up stuff

2021-05-18 07:14 UTC, HamletDRC commented on tests/opc-plc-tests/MonitoringTestsBase.cs
> +                _subscription.Delete(true);
Is it possible for this line to throw an exception and prevent the unsubscribe in the line below?

2021-05-18 07:14 UTC, HamletDRC commented on tests/opc-plc-tests/PlcSimulatorFixture.cs
> +            // TODO shutdown simulator
seems important to shutdown simulator

2021-05-18 07:14 UTC, HamletDRC commented on tests/opc-plc-tests/PlcSimulatorFixture.cs
> +            if (e.Error.StatusCode == StatusCodes.BadCertificateUntrusted)
Might be worth adding a little logging to this function, given that the WIndows folks are having security issues running tests.

2021-05-18 07:32 UTC, algattik commented on tests/opc-plc-tests/PlcSimulatorFixture.cs
> +            if (e.Error.StatusCode == StatusCodes.BadCertificateUntrusted)
Thanks. It seems the issues are actually related to the server's own certificate management (rather than client-side)

2021-05-18 07:34 UTC, algattik commented on tests/opc-plc-tests/PlcSimulatorFixture.cs
> +            // TODO shutdown simulator
As long as tests are run in a dedicated short-lived process, and the simulator is not doing any sensitive I/O such as opening files etc., not shutting down the simulator has no impact. 

Obviously it should still be done for cleanliness, but I think we can already go ahead like this as a first version

2021-05-18 07:34 UTC, algattik commented on src/PlcSimulation.cs
> +            bool nextAlternatingBoolean = _alternatingBooleanCycleInPhase % SimulationCycleCount == 0 ? !value : value;
Correct, this was an apparent copy-paste error in the original code. I fixed it so that tests correspond to documentation. Worth keeping track of

2021-05-18 07:35 UTC, algattik commented on src/PlcNodeManager.cs
> +                var m = dateTime.Millisecond;
Sorry, need to remove this line

2021-05-18 08:47 UTC, algattik commented on tests/opc-plc-tests/MonitoringTestsBase.cs
> +                _subscription.Delete(true);
Not clear, also why do we need to do two calls to remove a subscription... But this is how this is done in multiple samples in the OPC-UA .NET and Samples repos

2021-05-18 08:47 UTC, algattik commented on tests/opc-plc-tests/PlcSimulatorFixture.cs
> +            // TODO shutdown simulator
Created Task for this

2021-05-18 08:49 UTC, algattik commented on src/PlcSimulation.cs
> +            bool nextAlternatingBoolean = _alternatingBooleanCycleInPhase % SimulationCycleCount == 0 ? !value : value;
Created Task for this

2021-05-18 08:56 UTC, algattik commented
Thanks, I've added a README file on how to solve the issue for now

2021-05-18 09:07 UTC, merged