Implementation of FastTimer
simonjaeger/iot-edge-opc-plc pull request #13
Opened 2021-05-19 11:20 UTC by peterbryntesson

## Purpose
This PR introduces the new FastTimer class and it's use for when we want really high-frequency changes for fast nodes.

## Does this introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
```
Run the opc-publisher with --vfr=49 or below

* Test the code

```
* Run the test suite
```

2021-05-19 12:07 UTC, buzzfrog commented on src/PlcNodeManager.cs
> +        public void UpdateVeryFastNodes(object state, FastTimerElapsedEventArgs elapsedEventArgs)
Do we really need to methods with the same code?

2021-05-19 12:12 UTC, peterbryntesson commented on src/PlcNodeManager.cs
> +        public void UpdateVeryFastNodes(object state, FastTimerElapsedEventArgs elapsedEventArgs)
Well, we need two outer methods - but may then can call the same internal function. I'll refactor.

2021-05-19 12:14 UTC, buzzfrog commented on src/TimeService.cs
> +                if (diff < 1f)
Is our coding standard in this project that we don't need {} for one liners?

2021-05-19 12:15 UTC, peterbryntesson commented on src/TimeService.cs
> +                if (diff < 1f)
Yes

2021-05-19 12:16 UTC, buzzfrog commented
LGTM

2021-05-19 12:44 UTC, buzzfrog commented
LGTM

2021-05-19 12:47 UTC, buzzfrog approved these changes

2021-05-19 13:18 UTC, simonjaeger commented on src/TimeService.cs
> +            if (!isRunning)
Is there a potential problem if two threads access the timer and try to start it? Potential race condition?

2021-05-19 13:19 UTC, simonjaeger approved these changes
Really cool! LGTM

2021-05-19 13:19 UTC, simonjaeger commented on src/PlcSimulation.cs
> +                _fastNodeGenerator = FastNodeRate >= 50 ?
Great!

2021-05-19 13:20 UTC, peterbryntesson commented on src/TimeService.cs
> +            if (!isRunning)
Yes, I was waiting for someone to spot this... I'll guard this. Must run now but I'll fix it tonight.

2021-05-19 15:28 UTC, algattik requested changes
Test fails on my machine:

OpcPlc.Tests.FastTimerTests.FastTimer_ShouldFire_100TimesPerSecond

Expected _callbacks.Count to be between 199 and 201, but found 1.

2021-05-19 15:28 UTC, algattik commented on src/PlcSimulation.cs
> +                // only use the fast timers when we need to go really fast
maybe explain the reason (i.e. the FastTimer uses more resources)

2021-05-19 15:28 UTC, algattik commented on src/PlcSimulation.cs
> +                // only use the fast timers when we need to go really fast
nit: should we consider using only FastTimers? That might simplify the codebase

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +        public FastTimerElapsedEventArgs()
delete?

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +            : base()
```suggestion
```

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +                    if (intervalLocal != newInterval)
Equality comparison of floating point numbers. Possible loss of precision while rounding values

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +        private static readonly float tickFrequency = 1000f / Stopwatch.Frequency;
```suggestion
        private static readonly float TickFrequency = 1000f / Stopwatch.Frequency;
```

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +        private bool isEnabled = true;
```suggestion
        private bool _isEnabled = true;
```
also for next line

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +                return this.isEnabled;
unnecessary uses of `this`

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +                return this.isEnabled;
```suggestion
                get => this.isEnabled;
```

2021-05-19 15:28 UTC, algattik commented on src/TimeService.cs
> +        public void Start()
why are these methods public? Since we have coverage only for their private use, they should probably be private

2021-05-19 20:07 UTC, peterbryntesson commented on src/PlcSimulation.cs
> +                // only use the fast timers when we need to go really fast
Yeah, maybe we should only use FastTimers. It's worth thinking about

2021-05-19 20:12 UTC, peterbryntesson commented
> Test fails on my machine:
> 
> OpcPlc.Tests.FastTimerTests.FastTimer_ShouldFire_100TimesPerSecond
> 
> Expected _callbacks.Count to be between 199 and 201, but found 1.

Fixed

2021-05-19 20:13 UTC, peterbryntesson commented on src/PlcSimulation.cs
> +                // only use the fast timers when we need to go really fast
Nah, expanded on the comment instead.

2021-05-19 20:29 UTC, peterbryntesson commented on src/TimeService.cs
> +                    if (intervalLocal != newInterval)
If that happens it will only adjust the interval slightly.

2021-05-19 20:38 UTC, peterbryntesson commented
@algattik - addressed all your concerns. Mind giving it another look an approve if you think it's good?

2021-05-20 07:27 UTC, algattik approved these changes

2021-05-20 07:51 UTC, merged