Integration Tests for Boiler
simonjaeger/iot-edge-opc-plc pull request #19
Opened 2021-05-20 12:00 UTC by HamletDRC

## Purpose
Integration tests for Boiler

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2021-05-20 12:01 UTC, HamletDRC commented on tests/opc-plc-tests/BoilerTests.cs
> +        public void shouldStartTurnedOn()
what are the naming conventions for integration test methods?

2021-05-20 15:20 UTC, algattik commented on tests/opc-plc-tests/BoilerTests.cs
> +        public void shouldStartTurnedOn()
Usually ObjectOfTest_WhenConditions_ThenExpectation, or ObjectOfTest_Expectation

2021-05-21 05:06 UTC, HamletDRC commented on tests/opc-plc-tests/BoilerTests.cs
> +            InvokeHeaterMethod("HeaterOn");
TearDown is executed after each test method, while OneTimeTearDown is executed after each class: 
https://docs.nunit.org/articles/nunit/writing-tests/attributes/teardown.html

The simulator is stateful, and there is a risk of chained tests where one failing test can leave the header off. 

I think it best to leave this code.

2021-05-21 05:10 UTC, HamletDRC commented on tests/opc-plc-tests/BoilerTests.cs
> +            return (value as ExtensionObject).Body as BoilerModel.BoilerDataType;
ok

2021-05-21 05:17 UTC, HamletDRC commented on tests/opc-plc-tests/BoilerTests.cs
> +        public void shouldStartTurnedOn()
ok

2021-05-21 05:32 UTC, HamletDRC commented on tests/opc-plc-tests/BoilerTests.cs
> +            var methodNode = NodeId.Create(methodName, OpcPlc.Namespaces.OpcPlcBoiler, Session.NamespaceUris);
@algattik  can you please check my latest commit and let me know if you still think your comment is relevant? 

In the latest commit there are three helper functions: 
* TurnHeaterOn, TurnHeaterOff, and GetBoilerModel

All of the OPC related API calls are encapsulated into those three methods and there is no trace of OPC API in the test methods themselves. 

I could move the NodeId.Create calls into a SetUp method, but that means sprinkling more OPC API info across the file. IMO, I would leave it as-is (now that I refactored a little further)

2021-05-21 07:35 UTC, algattik requested changes

2021-05-21 07:35 UTC, algattik commented on tests/opc-plc-tests/BoilerTests.cs
> +    /// Tests for the variables defined in the simulator, such as fast-changing and trended nodes.
Text should be changed

2021-05-24 09:04 UTC, merged